# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20131213002823) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "matches", force: true do |t|
    t.string "serv_area_name"
    t.string "iop"
    t.string "hsp_account_id"
    t.string "pat_mrn_id"
    t.string "pat_name"
    t.string "medicare_id"
    t.string "medicaid_id"
    t.string "account_class"
    t.string "har_adm_date"
    t.string "har_disch_date"
    t.string "prim_enc_csn_id"
    t.string "dsch_department"
    t.string "fc_on_transaction"
    t.string "payor_on_transaction"
    t.string "payor_on_bucket"
    t.string "fin_class_name_1"
    t.string "payor_name_1"
    t.string "fin_class_name_2"
    t.string "payor_name_2"
    t.string "fin_class_name_3"
    t.string "payor_name_3"
    t.string "fin_class_name_4"
    t.string "payor_name_4"
    t.string "total_selfpay_payments"
    t.string "total_non_medicare_insurance_pymts"
    t.string "total_medicare_insurance_pymts"
    t.string "total_contractual_adj"
    t.string "balance_primary_coverage"
    t.string "transaction_type"
    t.string "write_off_date"
    t.string "service_date"
    t.string "tx_comment"
    t.string "y"
    t.string "proc_id"
    t.string "proc_code"
    t.string "proc_name"
    t.string "transaction_amount"
    t.string "x"
    t.string "bucket_id"
    t.string "bucket_type"
    t.string "claim_form"
  end

  create_table "records", force: true do |t|
    t.integer "provider_id"
    t.string  "provider_name"
    t.string  "provider_fye"
    t.string  "report_type"
    t.string  "report_num"
    t.string  "paid_from"
    t.string  "paid_to"
    t.string  "report_run_date"
    t.string  "service_period_num"
    t.string  "service_period_from"
    t.string  "service_period_thru"
    t.string  "service_from"
    t.string  "service_thru"
    t.string  "patient_name"
    t.string  "patient_control_num"
    t.string  "med_record_num"
    t.string  "hic_num"
    t.string  "receipt_date"
    t.string  "paid_date"
    t.string  "dcn"
    t.string  "bill_freq"
    t.string  "trans_type"
    t.string  "pricer_rtn_cd"
    t.string  "processor_id"
    t.string  "zip_code"
    t.string  "esrd_condition_code"
    t.string  "weight"
    t.string  "height"
    t.string  "birth_date"
    t.string  "claim_num"
    t.string  "rev_code"
    t.string  "description"
    t.string  "hcpcs"
    t.string  "panel_code"
    t.string  "trip_mile_ind"
    t.string  "units"
    t.string  "charges"
    t.string  "gross_fee_amt"
    t.string  "gross_reimb"
    t.string  "gapc"
    t.string  "outlier"
    t.string  "deductibles"
    t.string  "cash_deduct"
    t.string  "blood_deduct"
    t.string  "coins"
    t.string  "msp"
    t.string  "med_days"
    t.string  "esrd_rdctn_ntwk_payments"
    t.string  "msp_recon"
    t.string  "other_adjs"
    t.string  "line_item_reimb"
    t.string  "elected_coins"
    t.string  "mods"
    t.string  "service_ind"
    t.string  "pymt_ind"
    t.string  "dscnt_fct"
    t.string  "tob_incl"
    t.string  "apc"
    t.string  "undup_days"
    t.string  "hours"
    t.string  "gross_fee_reimb"
    t.string  "stndrd_ovrhd_amount"
    t.string  "tot_gross_fee_sched"
    t.string  "psr_report"
    t.string  "net_reimb"
    t.string  "msp_cash_deduct"
    t.string  "msp_blood_deduct"
    t.string  "msp_deductibles"
    t.string  "msp_coins"
    t.string  "patient_cbsa"
    t.string  "claim_interest"
    t.string  "claim_report_splits"
    t.string  "low_volume"
    t.string  "rebilling_adjustment"
  end

end
