class CreateRecords < ActiveRecord::Migration
  def change
    create_table :records do |t|
      t.integer :provider_id
      t.string :provider_name
      t.string :provider_fye
      t.string :report_type
      t.string :report_num
      t.string :paid_from
      t.string :paid_to
      t.string :report_run_date
      t.string :service_period_num
      t.string :service_period_from
      t.string :service_period_thru
      t.string :service_from
      t.string :service_thru
      t.string :patient_name
      t.string :patient_control_num
      t.string :med_record_num
      t.string :hic_num
      t.string :receipt_date
      t.string :paid_date
      t.string :dcn
      t.string :bill_freq
      t.string :trans_type
      t.string :pricer_rtn_cd
      t.string :processor_id
      t.string :zip_code
      t.string :esrd_condition_code
      t.string :weight
      t.string :height
      t.string :birth_date
      t.string :claim_num
      t.string :rev_code
      t.string :description
      t.string :hcpcs
      t.string :panel_code
      t.string :trip_mile_ind
      t.string :units
      t.string :charges
      t.string :gross_fee_amt
      t.string :gross_reimb
      t.string :gapc
      t.string :outlier
      t.string :deductibles
      t.string :cash_deduct
      t.string :blood_deduct
      t.string :coins
      t.string :msp
      t.string :med_days
      t.string :esrd_rdctn_ntwk_payments
      t.string :msp_recon
      t.string :other_adjs
      t.string :line_item_reimb
      t.string :elected_coins
      t.string :mods
      t.string :service_ind
      t.string :pymt_ind
      t.string :dscnt_fct
      t.string :tob_incl
      t.string :apc
      t.string :undup_days
      t.string :hours
      t.string :gross_fee_reimb
      t.string :stndrd_ovrhd_amount
      t.string :tot_gross_fee_sched
      t.string :psr_report
      t.string :net_reimb
      t.string :msp_cash_deduct
      t.string :msp_blood_deduct
      t.string :msp_deductibles
      t.string :msp_coins
      t.string :patient_cbsa
      t.string :claim_interest
      t.string :claim_report_splits
      t.string :low_volume
      t.string :rebilling_adjustment
    end
  end
end
